#
# Traefik - Maps containers to public FQDNs accessable via https with valid certs
#
  traefik:
    image: traefik:latest
    container_name: ${TRAEFIKNAME}
    hostname: ${TRAEFIKNAME}
    domainname: ${MYDOMAIN}
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CONFIGS}/${TRAEFIKNAME}/acme/acme.json:/acme.json
      - ${CONFIGS}/${TRAEFIKNAME}/traefik.toml:/traefik.toml
      - ${CONFIGS}/${TRAEFIKNAME}/traefik_secure.toml:/traefik_secure.toml
      - ${CONFIGS}/${TRAEFIKNAME}/traefik.log:/traefik.log
      - ${OMNIHOME}/healthchecks/traefikcheck:/traefikcheck
    labels:
      - "omni=${TRAEFIKNAME},${MYDOMAIN},yes,yes,yes"
      - autoheal=true
    networks:
      - OmniNet
    healthcheck:
      test: ["CMD-SHELL", "/traefikcheck"]
      interval: 10s
      timeout: 2s
      retries: 3

#
# OAuth - Forward Authentication
#

  oauth:
    image: thomseddon/traefik-forward-auth:latest
    container_name: ${OAUTHNAME}
    hostname: ${OAUTHNAME}
    domainname: ${MYDOMAIN}
    restart: unless-stopped
    networks:
      - OmniNet
    security_opt:
      - no-new-privileges:true
    environment:
      PROVIDERS_GOOGLE_CLIENT_ID: ${OAUTHID}
      PROVIDERS_GOOGLE_CLIENT_SECRET: ${OAUTHSECRET}
      SECRET: ${OAUTHSUPERSECRET}
      CONFIG: /configs/authdomains
      COOKIE_DOMAIN: ${MYDOMAIN}
      COOKIE-NAME: _forward_auth_csrf
      INSECURE_COOKIE: "false"
      AUTH_HOST: ${OAUTHNAME}.${MYDOMAIN}
      WHITELIST: ${OAUTHUSER}
      LOG_LEVEL: info
      LIFETIME: 2592000 # 30 days
      DEFAULT_ACTION: allow
      DEFAULT_PROVIDER: google
    labels:
      - "omni=${OAUTHNAME},${MYDOMAIN},yes,yes,yes"
      - autoheal=true
      - traefik.enable=true
      - traefik.http.middlewares.oauth.forwardauth.address=http://oauth:4181
      - traefik.http.middlewares.oauth.forwardauth.authResponseHeaders=X-Forwarded-User
      - traefik.http.middlewares.oauth.forwardauth.trustForwardHeader=true
      - traefik.http.routers.oauth.rule=Host(`${OAUTHNAME}.${MYDOMAIN}`)
      - traefik.http.routers.oauth.tls=true
      - traefik.http.routers.oauth.tls.certresolver=lets-encrypt
      - traefik.http.services.oauth.loadbalancer.server.port=4181
    volumes:
      - ${CONFIGS}/${OAUTHNAME}:/configs:ro
